config/routes.rb
Rails.application.routes.draw do
  resources :promotions
  resources :categories
  resources :orders
  resources :line_items
  delete '/carts/:id', to: 'carts#destroy'
  resources :carts
  resources :admin_user_mfa_session, only: [:new, :create]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'store/index'
  resources :products do
    get :who_bought, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'categories#index', as: 'store'
  namespace :admin_user do
    root to: 'categorie#index'
  end
end

app/models/order.rb
class Order < ApplicationRecord
  PAYMENT_TYPES = ["Наличные", "Картой"]
  has_many :line_items, dependent: :destroy
  validates :name, :address, :email, :phone_number, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base
include CurrentCart
before_action :set_cart, only: [:new, :create]


def index
  if can? :read, @order
    @orders = Order.where(email: current_admin_user.email)
  end
end

def show
  if can? :read, @order
    @order = Order.find(params[:id])
  end
end

def create
    @order = Order.new(order_params)
    if current_admin_user
      @order.email = current_admin_user.email
    end
    @order.add_line_items_from_cart(@cart)
    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        OrderNotifierMailer.received(@order).deliver
        format.html {redirect_to store_url, notice: 'Thank u for ur order'}
        format.json {render action: 'show', status: :created, location: @order}
      else
        format.html {render action: 'new'}
        format.json { render json: @order.errors, status: :unprocessable_entity}
      end
    end
end

def new
    if @cart.line_items.empty?
      redirect_to store_url, notice: 'Your cart is empty'
      return
    end
    @order=Order.new
end

def destroy
  @order = Order.find(params[:id])
  if current_admin_user.email == @order.email
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
  end
  end
end

  private

    def order_params
      params.require(:order).permit(:name, :address, :email, :pay_type, :phone_number, :id)
    end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
    <% if @order.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@order.errors.count, "error") %>
            prohibited this order from being saved:</h2>
          <ul>
            <% @order.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :Ваше_имя %><br>
      <%= f.text_field :name, size: 40 %>
    </div>
    <div class="field">
      <%= f.label :Адрес_доставки %><br>
      <%= f.text_area :address, rows: 3, cols: 40 %>
    </div>
    <div class="field">
      <%= f.label :Номер_телефона %><br>
      <%= f.text_field :phone_number, size: 15 %>
    </div>
    <% unless current_admin_user %>
      <div class="field">
        <%= f.label :Адрес_электронной_почты %><br>
        <%= f.email_field :email, size: 40 %>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :Способ_оплаты %><br>
      <%= f.select :pay_type, Order::PAYMENT_TYPES,
                    prompt: 'Выберите способ оплаты' %>
    </div>
    <div class="actions">
      <%= f.submit 'Оформить заказ' %>
    </div>
<% end %>

app/views/orders/edit.html.erb
<% unless current_admin_user && current_admin_user.email == @order.email %>
     <% controller.redirect_to store_url %>
<% end %>

<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<% unless current_admin_user && current_admin_user.role !='banned' %>
    <% controller.redirect_to store_url %>
<% end %>
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Pay type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <% if current_admin_user.email == order.email %>
          <td><%= order.name %></td>
          <td><%= order.address %></td>
          <td><%= order.email %></td>
          <td><%= order.pay_type %></td>
          <td><%= link_to 'Show', order %></td>
          <td><%= link_to 'Edit', edit_order_path(order) %></td>
          <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/orders/new.html.erb
<div class="depot_form">
  <fieldset>
    <legend>Pls enter ur details</legend>
    <%= render 'form' %>
  </fieldset>
</div>

app/views/orders/show.html.erb
<% unless current_admin_user && current_admin_user.email == @order.email %>
    <% controller.redirect_to store_url %>
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Pay type:</strong>
  <%= @order.pay_type %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>