config/routes.rb
Rails.application.routes.draw do
  resources :promotions
  resources :categories
  resources :orders
  resources :line_items
  delete '/carts/:id', to: 'carts#destroy'
  resources :carts
  resources :admin_user_mfa_session, only: [:new, :create]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'store/index'
  resources :products do
    get :who_bought, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'categories#index', as: 'store'
  namespace :admin_user do
    root to: 'categorie#index'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  validates :title, presence: true
  validates_numericality_of :price , {:greater_than_or_equal_to => 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
      with: %r{\.(gif|jpg|jpeg|png)\Z}i,
      message: 'URL должен указывать на изображение формата GIF, JPG, JPEG или PNG.'
  }
  def self.latest
    Product.order(:updated_at).last
  end

  def self.search(search)
    if search
      product = Product.joins(:category).where("products.title LIKE ? OR products.description LIKE ? OR categories.name LIKE ? OR concat_ws(' ', categories.name, products.title) LIKE ? OR concat_ws(' ', categories.name, products.description) LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
      if product
        self.where(id: product)
      else
        Product.all
      end
    else
      Product.all
    end
  end



  private

  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
  else
    errors.add(:base, 'line items insist')
    return false
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include CurrentCart
  before_action :set_cart
  before_action :set_product, only: [:show, :edit, :update, :destroy]
attr_accessor

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.older(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
      end
    end
  end

  def index
    if can? :read, @product
      @products = Product.search(params[:search])
    end
  end

  def show
    if can? :read, @product
      @product=Product.find(params[:id])
    end
  end


  def new
    if can? :create, @product
      @product = Product.new
    end
  end


  def edit
    end


  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    if can? :update, @product
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to @product, notice: 'Product was successfully updated.' }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { render :edit }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end
  end


  def destroy
    if can? :destroy, @product
      @product.destroy
      respond_to do |format|
        format.html { redirect_to products_url, notice: 'Товар был успешно удален' }
        format.json { head :no_content }
      end
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :search, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :desription, rows: 6 %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<% if cannot? :update, @product %>
  <% controller.redirect_to store_url %>
<% end %>
<h1>Editing Product</h1>
<%= render 'form', product: @product %>
<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Каталог товаров</h1>

  <table>
    <% @products.each do |product| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even')%>">
        <td>
          <%= image_tag(product.image_url, class: 'list_image') %>
        </td>
        <td class="list_description">
          <dl>
            <dt><%category = Category.find_by(id: product.category_id) %></dt>
            <dt><%= category.name %></dt>
            <dt><%= product.title %></dt>
            <dd><%= truncate(strip_tags(product.description), length: 80) %></dd>
          </dl>
        </td>
        <td class="list_actions">
          <li><%= link_to 'Посмотреть', product %><br/></li>
          <div class="price_line">
            <span class="price"><%= number_to_currency(product.price) %></span>
            <%= button_to 'В корзину', line_items_path(product_id: product), remote: true %>
          </div>
        </td>
      </tr>
      <% end %>
  </table>
  <br />

app/views/products/new.html.erb
<% if cannot? :create, @product %>
    <% controller.redirect_to store_url %>
<% end %>
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Описание:</strong>
  <%= @product.description %>
</p>

<p>
  <%= image_tag(@product.image_url, class: 'list_image') %>
</p>

<p>
  <strong>Цена:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Назад', products_path %>